# -*- coding: utf-8 -*-
#
#   Dao-Ke-Dao: Universal Message Module
#
#                                Written in 2019 by Moky <albert.moky@gmail.com>
#
# ==============================================================================
# MIT License
#
# Copyright (c) 2019 Albert Moky
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ==============================================================================

from abc import ABC, abstractmethod

from dimp import ReliableMessage


class ReliableMessageDelegate(ABC):  # (SecureMessageDelegate, ABC):

    """Delegate interface for verifying ReliableMessage signatures.

    Handles the final verification step to convert ReliableMessage back to
    SecureMessage by validating the sender's signature.
    """

    #
    #   Verify the Reliable Message to Secure Message
    #
    #     +----------+      +----------+
    #     | sender   |      | sender   |
    #     | receiver |      | receiver |
    #     | time     |  ->  | time     |
    #     |          |      |          |
    #     | data     |      | data     |  1. verify(data, signature, sender.PK)
    #     | keys     |      | keys     |
    #     | signature|      +----------+
    #     +----------+

    # @abstractmethod
    # async def decode_signature(self, signature: Any, msg: ReliableMessage) -> Optional[bytes]:
    #     """
    #     1. Decode 'message.signature' from String (Base64)
    #
    #     :param signature: base64 string
    #     :param msg:       reliable message
    #     :return: signature data
    #     """
    #     raise NotImplementedError(
    #         f'Not implemented: {type(self).__module__}.{type(self).__name__}.decode_signature()'
    #     )

    @abstractmethod
    async def verify_data_signature(self, data: bytes, signature: bytes, msg: ReliableMessage) -> bool:
        """Verifies encrypted content data against sender's signature (Step 2).

        Uses the sender's public key (from Meta/Visa) to validate that the
        signature was generated by the sender's private key (authenticity check).

        :param data:      message content(encrypted) data
        :param signature: signature of message content(encrypted) data
        :param msg:       reliable message
        :return: True on signature matched
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.verify_data_signature()'
        )
