# -*- coding: utf-8 -*-
#
#   DIMP : Decentralized Instant Messaging Protocol
#
#                                Written in 2019 by Moky <albert.moky@gmail.com>
#
# ==============================================================================
# MIT License
#
# Copyright (c) 2019 Albert Moky
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ==============================================================================

import weakref
from typing import Optional

from dimp import SecureMessage, ReliableMessage

from .reliable_delegate import ReliableMessageDelegate


class ReliableMessagePacker:

    """Packer class for verifying ReliableMessage signatures.

    Validates the sender's signature on a ReliableMessage and converts it back to
    a SecureMessage if the signature is authentic.
    """

    def __init__(self, messenger: ReliableMessageDelegate):
        super().__init__()
        self.__transformer = weakref.ref(messenger)

    @property
    def delegate(self) -> Optional[ReliableMessageDelegate]:
        return self.__transformer()

    #
    #   Verify the Reliable Message to Secure Message
    #
    #     +----------+      +----------+
    #     | sender   |      | sender   |
    #     | receiver |      | receiver |
    #     | time     |  ->  | time     |
    #     |          |      |          |
    #     | data     |      | data     |  1. verify(data, signature, sender.PK)
    #     | keys     |      | keys     |
    #     | signature|      +----------+
    #     +----------+

    async def verify_message(self, msg: ReliableMessage) -> Optional[SecureMessage]:
        """Verifies a ReliableMessage's signature and converts it to a SecureMessage.

        Validates that the 'signature' field was generated by the sender's private key
        (using their public key), and removes the signature field to return a SecureMessage.

        :param msg: network message
        :return: SecureMessage object if signature matched
        """
        transformer = self.delegate
        assert transformer is not None, 'reliable message delegate not found'

        #
        #   0. Decode 'message.data' to encrypted content data
        #
        msg_data = msg.data
        ciphertext = None if msg_data is None else msg_data.to_bytes()
        if ciphertext is None or len(ciphertext) == 0:
            # assert False, f'failed to decode message data: ' \
            #               f'{msg.sender} => {msg.receiver}, {msg.group}'
            return None

        #
        #   1. Decode 'message.signature' from String (Base64)
        #
        msg_sig = msg.signature
        signature = None if msg_sig is None else msg_sig.to_bytes()
        if signature is None or len(signature) == 0:
            # assert False, f'failed to decode message signature: ' \
            #               f'{msg.sender} => {msg.receiver}, {msg.group}'
            return None

        #
        #   2. Verify the message data and signature with sender's public key
        #
        ok = await transformer.verify_data_signature(data=ciphertext, signature=signature, msg=msg)
        if not ok:
            # assert False, f'message signature not match: ' \
            #               f'{msg.sender} => {msg.receiver}, {msg.group}'
            return None

        # OK, pack message
        info = msg.copy_map()
        info.pop('signature', None)
        return SecureMessage.parse(msg=info)
