# -*- coding: utf-8 -*-
#
#   DIM-SDK : Decentralized Instant Messaging Software Development Kit
#
#                                Written in 2019 by Moky <albert.moky@gmail.com>
#
# ==============================================================================
# MIT License
#
# Copyright (c) 2019 Albert Moky
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ==============================================================================

from abc import ABC, abstractmethod
from typing import Optional

from dimp import SymmetricKey
from dimp import ID
from dimp import Message


class CipherKeyDelegate(ABC):
    """Delegate interface for managing **directional symmetric encryption keys** in messaging.

    Core concept: Symmetric keys are direction-specific (unidirectional) between two parties:
    - User A → User B: Uses key1 (generated by A, for A→B messages only)
    - User B → User A: Uses key2 (generated by B, for B→A messages only)
    - Key1 ≠ Key2, both exist simultaneously during A↔B communication
    - Independent key pairs are generated for A↔C, B↔C, etc.

    Key features:
    1. Directionality: Keys are scoped to (sender → receiver) pairs (not bidirectional)
    2. Reusability: Cached keys can be reused for subsequent messages in the same direction
    3. Context awareness: Handles personal/group/broadcast message key management
    """

    #
    #   Message scenario matrix (key destination determination):
    #
    #                     +-------------+-------------+-------------+-------------+
    #                     |  receiver   |  receiver   |  receiver   |  receiver   |
    #                     |     is      |     is      |     is      |     is      |
    #                     |             |             |  broadcast  |  broadcast  |
    #                     |    user     |    group    |    user     |    group    |
    #       +-------------+-------------+-------------+-------------+-------------+
    #       |             |      A      |             |             |             |
    #       |             +-------------+-------------+-------------+-------------+
    #       |    group    |             |      B      |             |             |
    #       |     is      |-------------+-------------+-------------+-------------+
    #       |    null     |             |             |      C      |             |
    #       |             +-------------+-------------+-------------+-------------+
    #       |             |             |             |             |      D      |
    #       +-------------+-------------+-------------+-------------+-------------+
    #       |             |      E      |             |             |             |
    #       |             +-------------+-------------+-------------+-------------+
    #       |    group    |             |             |             |             |
    #       |     is      |-------------+-------------+-------------+-------------+
    #       |  broadcast  |             |             |      F      |             |
    #       |             +-------------+-------------+-------------+-------------+
    #       |             |             |             |             |      G      |
    #       +-------------+-------------+-------------+-------------+-------------+
    #       |             |      H      |             |             |             |
    #       |             +-------------+-------------+-------------+-------------+
    #       |    group    |             |      J      |             |             |
    #       |     is      |-------------+-------------+-------------+-------------+
    #       |    normal   |             |             |      K      |             |
    #       |             +-------------+-------------+-------------+-------------+
    #       |             |             |             |             |             |
    #       +-------------+-------------+-------------+-------------+-------------+
    #
    #       Scenario explanations:
    #         A: Personal message (1:1, directional key)
    #         B: (same to J)
    #         C: Broadcast to individual user (no encryption)
    #         D: (same to G)
    #         E: Broadcast group message to individual user (no encryption)
    #         F: Broadcast group message to any user (no encryption)
    #         G: Broadcast group message (receiver=group, no encryption, non-split)
    #         H: Group message targeted to individual member (split key)
    #         J: Standard group message (receiver=group, non-split)
    #         K: Unencrypted group command (broadcast receiver + normal group)

    @classmethod
    def destination_for_message(cls, msg: Message) -> ID:
        """Derives the key destination ID for a message (determines key scope).

        Maps the message's receiver/group context to a standard destination ID
        for key lookup/caching (follows the scenario matrix above).
        """
        receiver = msg.receiver
        group = ID.parse(identifier=msg.get('group'))
        return cls.get_destination(receiver=receiver, group=group)

    @classmethod
    def get_destination(cls, receiver: ID, group: Optional[ID]) -> ID:
        """Core method to determine key destination ID from receiver/group context.

        Handles scenario transformations:
        1. If group is null but receiver is group → map to group ID (B→J, D→G)
        2. If group is null → use receiver (personal/broadcast user message: A/C)
        3. If group is broadcast → use group ID (broadcast scenarios: E/F/G)
        4. If receiver is broadcast → use receiver (unencrypted group command: K)
        5. Otherwise → use group ID (standard group scenarios: H/J)

        `receiver` is the target receiver ID (user/group/broadcast).
        `group` is the optional group ID (null for personal messages).

        Returns the standardized destination ID for key management.

        Raises an assertion error if ID types are invalid (e.g., non-user receiver for personal message).
        """
        if group is None and receiver.is_group:
            # Transform:
            #     (B) => (J)
            #     (D) => (G)
            group = receiver
        # check group
        if group is None:
            # A : personal message (or hidden group message)
            # C : broadcast message for anyone
            assert receiver.is_user, f'receiver error: {receiver}'
            return receiver
        assert group.is_group, f'group error: {group}, receiver: {receiver}'
        if group.is_broadcast:
            # E : unencrypted message for someone
            #     return group as broadcast ID for disable encryption
            # F : broadcast message for anyone
            # G : (receiver == group) broadcast group message
            assert receiver.is_user or receiver == group, f'receiver error: {receiver}'
            return group
        elif receiver.is_broadcast:
            # K : unencrypted group message, usually group command
            #     return receiver as broadcast ID for disable encryption
            assert receiver.is_user, f'receiver error: {receiver}, group: {group}'
            return receiver
        else:
            # H    : group message split for someone
            # J    : (receiver == group) non-split group message
            return group

    @abstractmethod
    async def get_cipher_key(self, sender: ID, receiver: ID, generate: bool = False) -> Optional[SymmetricKey]:
        """
        Retrieves the directional symmetric key for (sender → receiver) communication.

        Key rules:
        - Returns the key specific to the sender→receiver direction (not reverse)
        - If key doesn't exist and `generate` is true → creates a new random key
        - If key doesn't exist and `generate` is false → returns null

        :param sender:   user or contact ID
        :param receiver: contact or user/group ID
        :param generate: generate when key not exists
        :return:         cipher key
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.get_cipher_key()'
        )

    @abstractmethod
    async def cache_cipher_key(self, key: SymmetricKey, sender: ID, receiver: ID):
        """
        Caches a directional symmetric key for reuse in (sender → receiver) communication.

        Key rules:
        - Stores the key under the exact (sender, receiver) pair (directional)
        - Overwrites any existing key for the same direction (sender→receiver)
        - Does not affect the reverse direction (receiver→sender) key

        :param key:      cipher key from a contact
        :param sender:   user or contact ID
        :param receiver: contact or user/group ID
        """
        raise NotImplementedError(
            f'Not implemented: {type(self).__module__}.{type(self).__name__}.cache_cipher_key()'
        )
